name: CI / CD

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2
  AWS_LIGHTSAIL_PROJECT: trinity
  AWS_LIGHTSAIL_SERVICE_NAME: trinity-front
  CONTAINER_TAG: $(date +%s)
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag trinity-front:${ env.CONTAINER_TAG }

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

          #- name: Install AWS CLI
          #run: |
          #curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          #unzip awscliv2.zip
          #sudo ./aws/install
          #aws --version
      
      - name: Install Lightsail
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Push Container Image
        run: |
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} \
            --label ${{ env.AWS_LIGHTSAIL_PROJECT }} \
            --image ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}:${ env.CONTAINER_TAG }

      - name: Deploy
        run: |
          aws lightsail get-container-images --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.front.image = $image' ./deploy/deploy-lightsail.json > container.json
          aws lightsail create-container-service-deployment --service-name ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }} --cli-input-json file://$(pwd)/container.json


